app/models.py
from .plugin import db



class Company(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    companyName = db.Column(db.String(20))
    companyType = db.Column(db.String(20))
    users = db.relationship('User',backref='company', lazy=True)

class User(db.Model):
    # 需要自行创建主键
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    username = db.Column(db.String(80))
    password = db.Column(db.String(20))
    age = db.Column(db.Integer)
    sex = db.Column(db.Boolean)
    job = db.Column(db.String(100))
    company_id = db.Column(db.Integer,db.ForeignKey(Company.id),nullable=True)
    token = db.Column(db.String(200),nullable=True)
    is_delete = db.Column(db.Boolean,default=False)

class Members(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(80),unique=True,nullable=False)
    password = db.Column(db.String(20),nullable=False)
    email = db.Column(db.String(120),unique=True,nullable=False)
    phone = db.Column(db.String(20),unique=True,nullable=True)
    token = db.Column(db.String(200),nullable=True)
    is_active = db.Column(db.Boolean,default=False,nullable=False)
    is_delete = db.Column(db.Boolean,default=False,nullable=False)

app/__init__.py
from flask import Flask
from . import views


def createapp():
    app = Flask(__name__)

    # 配置插件
    views.blue_init(app)

    return app

app/apis/__init__.py
from app.plugin import api
from . import apitest,company,sendemail,signin


api.add_resource(apitest.HelloWorld, '/api/v1/helloworld/')
api.add_resource(company.Company, '/api/v1/company/<int:id>/')
api.add_resource(company.Allcompany, '/api/v1/allcompany/')
api.add_resource(sendemail.SendEmailTest, '/api/v1/sendemailtest/')
api.add_resource(signin.SignUp, '/api/v1/signup/')
api.add_resource(signin.SignIn, '/api/v1/signin/')
api.add_resource(signin.ResetPassword, '/api/v1/resetpassword/')

app/views.py
import math, time
from datetime import timedelta

from flask import Blueprint, session, render_template, request, redirect, url_for, jsonify, g
from app.plugin import cache
from . import models,plugin

blue = Blueprint('first',__name__)

# 配置蓝图
def blue_init(app):
    app.register_blueprint(blueprint=blue)
    plugin.plugin_init(app)



@blue.route('/test/')
def test():
    return "success!"

# 设置 session http://10.20.152.50:8000/setsess/
@blue.route('/setsess/')
def setsess():
    session['key'] = 'value'
    session["sid"] = session.sid
    # print('打印出浏览器需要的 sessionid - value： ')
    # print(request.cookies.get('sessionid'))
    # print(type(request.cookies))
    # print(dir(request.cookies))
    # session.permanent = True
    # app.permanent_session_lifetime = timedelta(seconds=5)
    return 'set session success!'

# 获取 session
@blue.route('/getsess/')
def getsess():
    print(session.sid)
    result = session.get('sid','not find')
    return 'the session value of key is %s' % result

# get 请求转入 sessionid 根据指定 id 获取 session 中的内容
@blue.route('/getsessbysid/<sid>/')
def getsessbysid(sid):
    session.sid = sid
    result = session.get('sid','not find')
    return '[getsessbysid] the session value of key is %s' % result

# 随机增加 user 对象
@blue.route('/randomAddUser/')
def randomAddUser():
    import random
    randNum = random.randint(100,999)

    user = models.User()
    user.username = str(randNum) + 'jackMa'
    user.password = '123456'
    user.age = random.randint(16,32)
    user.sex = random.sample((True,False),1)[0]
    user.job = 'CEO of alibaba'

    models.db.session.add(user)
    models.db.session.commit()
    return 'success!'

# 客户端 form 表单增加对象
@blue.route('/addUser/', methods=['POST'])
def addUser():
    username = request.form.get("username")
    password = request.form.get("password")
    age = request.form.get("age")
    sex = request.form.get("sex")
    job = request.form.get("job")

    user = models.User()
    user.username = username
    user.password = password
    user.age = int(age)
    if sex == 'True':
        user.sex = 1
    else:
        user.sex = 0
    user.job = job

    models.db.session.add(user)
    models.db.session.commit()
    return redirect(url_for('first.queryUser'))


# 查询全部
@blue.route('/queryUser/')
def queryUser():

    users = models.User.query.all()
    print(len(users))
    # users = [models.user.query.get(4),]
    # users = models.user.query.filter(models.user.age == 24)
    # users = models.user.query.filter(models.user.age == 24).order_by(-models.user.id)
    # users = models.user.query.filter(models.user.age < 24).order_by(-models.user.age)
    # users = models.user.query.filter(models.user.age < 27).order_by(-models.user.age).limit(2)
    # users = models.user.query.filter().order_by(-models.user.age)
    # users = models.user.query.filter().order_by(-models.user.age).limit(2)
    # users = models.user.query.filter(models.user.age == 24).offset(1)
    # users = models.user.query.filter(models.user.age == 24).offset(1).limit(2)
    # users = models.user.query.filter(models.user.age == 24).limit(2).offset(1)
    # limit 始终是最后执行

    # 包含
    #users = models.user.query.filter(models.user.id.in_([1,5,6,8,12,15,20,21,25]))

    # 模糊查询
    # users = models.user.query.filter(models.user.username.startswith('2'))
    # users = models.User.query.filter(models.User.username.like('%3%'))
    return render_template("user/user.html",users=users)

# 查询分页，一页6个
@blue.route('/queryUserByPage/<int:pageNum>/')
@cache.cached(timeout=50)
def queryUserByPage(pageNum):
    all_user = models.User.query.all()
    total_pages = range(1,math.ceil(len(all_user)/6)+1)
    start = 6 * (pageNum - 1)
    end = start + 6
    users = all_user[start:end]

    return render_template("user/user.html",users=users,totalPages=total_pages)

# 根据 ID 删除
@blue.route('/deleteUser/<int:userId>')
def deleteUser(userId):
    # 删除
    try:
        users = [models.User.query.get(userId), ]
        models.db.session.delete(users[0])
        models.db.session.commit()
    except:
        pass

    return redirect(url_for('first.queryUser'))

# 批量删除
@blue.route('/deleteUser/')
def bulkDeleteUser():

    # 批量删除 - 渲染模板时 users 获取不到。
    users = models.User.query.filter(models.User.age < 20)
    for user in users:
        models.db.session.delete(user)
    models.db.session.commit()

    return render_template("user.html")


@blue.route('/editUser/<int:userId>',methods=['POST'])
def editUser(userId):
    user = models.User.query.get(userId)
    username = request.form.get("username")
    password = request.form.get("password")
    age = request.form.get("age")
    sex = request.form.get("sex")
    job = request.form.get("job")

    user.username = username
    user.password = password
    user.age = int(age)
    if sex == 'True':
        user.sex = 1
    else:
        user.sex = 0
    user.job = job

    models.db.session.add(user)
    models.db.session.commit()

    return redirect(url_for('first.queryUser'))

# 勾子函数，类似于中间件
@blue.before_request
def beforerequest():
    print("this requester id is: {}".format(request.remote_addr))


# jsonify 方法
@blue.route('/jsonify/')
def jsonifyTest():
    data = {
        "id":1,
        "name":"data",
        "age":24
    }

    response = {
        'status': 200,  # 状态码
        'time':time.time(), # 请求时间
        'message':"Success!",   # 提示信息
        'data':[data,],
    }
    return jsonify(response)
    # return str(response)

app/templates/base/base.html
{% extends "bootstrap/base.html" %}


{%- block styles %}
<!-- Bootstrap -->
{#<link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">#}
{{ super() }}
<link href="/static/css/base.css" rel="stylesheet">
{%- endblock styles %}




{% block navbar %}
<div id="head-form">
<form class="navbar-form navbar-left" role="search">
    <span id="head-logo">AUKEY</span>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>
{%- endblock navbar %}

app/templates/studentbase.html
{% extends "bootstrap/base.html" %}


{%- block styles %}
<!-- Bootstrap -->
{#<link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">#}
{{ super() }}
<link href="/static/css/base.css" rel="stylesheet">
{%- endblock styles %}




{% block navbar %}

<form class="navbar-form navbar-left" role="search">
    <span id="head-logo">AUKEY</span>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>
{%- endblock navbar %}

{% block content %}

{% endblock %}

app/templates/user/user.html
{% extends "base/base.html" %}
{%- block styles %}
{{ super() }}
<link href="/static/css/user/user.css" rel="stylesheet">
{%- endblock styles %}


{% block navbar %}
{{ super() }}
<button type="button" id="head-add" class="btn btn-default" data-toggle="modal" data-target="#myModal">添加</button>

{%- endblock navbar %}




{% block content %}
<div id="main-table">
    <div>
    <table class="table table-hover">
        <tr>
            <th>id</th>
            <th>user name</th>
            <th>password</th>
            <th>age</th>
            <th>sex</th>
            <th>job</th>
            <th>删除</th>
            <th>修改</th>
        </tr>
        {% for user in users %}
        <tr>

            <td>{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.password }}</td>
            <td>{{ user.age }}</td>
            <td>{{ user.sex }}</td>
            <td>{{ user.job }}</td>
            <td><a href="{{ url_for("first.deleteUser",userId=user.id) }}" >删除</a></td>
            <td><a data-toggle="modal" data-target="#myModal{{ user.id }}" >修改</a></td>
        </tr>

        <!-- Modal -->
        <div class="modal fade" id="myModal{{ user.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">修改</h4>
                    </div>
                    <div class="modal-body">
<!-------------- 修改表单开始 ---------------->
                        <form action="{{ url_for("first.editUser",userId=user.id)  }}" method="POST">
                            <div class="form-group">
                                <label for="">User Name</label>
                                <input type="text" class="form-control" name="username" value="{{ user.username }}">
                            </div>
                            <div class="form-group">
                                <label for="">Password</label>
                                <input type="text" class="form-control" name="password" value="{{ user.password }}">
                            </div>
                            <div class="form-group">
                                <label for="">Age</label>
                                <input type="text" class="form-control" name="age" value="{{ user.age }}">
                            </div>
                            <div class="form-group">
                                <label for="">Sex</label>
                                <input type="text" class="form-control" name="sex" value="{{ user.sex }}">
                            </div>
                            <div class="form-group">
                                <label for="">Job</label>
                                <input type="text" class="form-control" name="job" value="{{ user.job }}">
                            </div>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </form>
<!-------------- 修改表单结束 ---------------->
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}

    </table>
    </div>


    <!--------------- pagination start --------------->
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for page in totalPages %}
            <li><a href="{{ url_for('first.queryUserByPage',pageNum=page) }}" >{{ page }}</a></li>
            {% endfor %}
{#            <li><a href="{{ url_for('first.queryUserByPage',2) }}" >2</a></li>#}
{#            <li><a href="{{ url_for('first.queryUserByPage',3) }}" >3</a></li>#}
{#            <li><a href="{{ url_for('first.queryUserByPage',4) }}" >4</a></li>#}
{#            <li><a href="{{ url_for('first.queryUserByPage',5) }}" >5</a></li>#}
            <li>
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    <!--------------- pagination end --------------->


</div>



<!-- head-add Modal start -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
<!-------------- head-add 增加 开始 ---------------->
                        <form action="{{ url_for("first.addUser") }}" method="POST">
                            <div class="form-group">
                                <label for="">User Name</label>
                                <input type="text" class="form-control" name="username" placeholder="username">
                            </div>
                            <div class="form-group">
                                <label for="">Password</label>
                                <input type="text" class="form-control" name="password" placeholder="password">
                            </div>
                            <div class="form-group">
                                <label for="">Age</label>
                                <input type="text" class="form-control" name="age" placeholder="age">
                            </div>
                            <div class="form-group">
                                <label for="">Sex</label>
                                <input type="text" class="form-control" name="sex" placeholder="True or False">
                            </div>
                            <div class="form-group">
                                <label for="">Job</label>
                                <input type="text" class="form-control" name="job" placeholder="job">
                            </div>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </form>
<!-------------- head-add 增加 结束 ---------------->

            </div>
        </div>
    </div>
</div>
<!-- head-add Modal end -->


{% endblock %}